name: CI Tests

on:
  push:
  pull_request:

jobs:
  unit-and-bdd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

    #  - name: Install tools
      #  run: |
         # go install github.com/cucumber/godog/cmd/godog@latest
      - name: Run unit tests
        run: |
          go test ./...
   #   - name: Run BDD features
   #     run: |
          # godog run ./features
